use master
drop database if exists TestsDB
create database TestsDB
use TestsDB

CREATE TABLE STUDENT(
		ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		Surname NVARCHAR(50),
		Name_ NVARCHAR(50),
		Patronymic NVARCHAR(50),
		Group_ NVARCHAR(50),
)
CREATE TABLE TEST(
		ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		Name_ NVARCHAR(50),
)
CREATE TABLE TESTRESULT(
		ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		STUDENT_ID INT REFERENCES STUDENT(ID),
		TEST_ID INT REFERENCES TEST(ID),
		MARK INT,
)